Create CONTRIBUTING.md
Ibexoft/ibex-wallet pull request #105
Opened 2024-10-21 16:38 UTC by MuhammadMaazFaisal

2024-10-21 16:49 UTC, mjawaids requested changes

2024-10-21 16:49 UTC, mjawaids commented on CONTRIBUTING.md
> +We appreciate your help and look forward to future contributions!
Please, add Laiba as she does contribute as a QA.

2024-10-22 13:53 UTC, MuhammadMaazFaisal commented on CONTRIBUTING.md
> +We appreciate your help and look forward to future contributions!
Done

2024-10-22 16:19 UTC, mjawaids approved these changes

2024-10-22 16:20 UTC, merged