user is not able make transfer transaction withing same account
Ibexoft/ibex-wallet pull request #130
Opened 2024-12-15 13:58 UTC by MHamzaBham

2024-12-15 14:07 UTC, mjawaids requested changes

2024-12-15 14:07 UTC, mjawaids commented on resources/views/transactions/create-widget.blade.php
> +        srcAccountDropdown.addEventListener('change', () => {
I haven't tested it yet but it seems if user has accounts CASH, BANK, and MOBILE for example, and user selects CASH in source then it would be removed from destination account which is fine, but if user selects BANK in the destination account then it will be removed from the source account which is incorrect because what if user wants to change their selection in source account to BANK? They won't be able to do that easily. Removing only from destination would be sufficient and changing source would do the trick.

2024-12-18 15:26 UTC, MHamzaBham commented on resources/views/transactions/create-widget.blade.php
> +        srcAccountDropdown.addEventListener('change', () => {
This approach is letting the user selecting the same account on both, if user selects BANK on destination and the BANK on source aswell and make a trasaction then it lets the user make the transaction

2024-12-18 19:24 UTC, mjawaids approved these changes

2024-12-18 19:24 UTC, merged