Add Configuration files
Ibexoft/ibex-wallet pull request #79
Opened 2024-08-27 18:36 UTC by MuhammadMaazFaisal

2024-08-27 18:44 UTC, mjawaids requested changes

2024-08-27 18:44 UTC, mjawaids commented on composer.json
> +    "name": "ibexoft/ibexpenses",
Convert it to 'ibexoft/ibex-wallet'

2024-08-27 18:44 UTC, mjawaids commented on README.md
> +# Ibexpenses
Convert the name to Ibex Wallet (ibex-wallet) everywhere you see.

2024-08-27 18:44 UTC, mjawaids commented on README.md
> +(UNDER ACTIVE DEVELOPMENT. NOT EVEN IN 'BETA')
If code build/setup steps can be added would be great.

2024-08-27 18:44 UTC, mjawaids commented on composer.json
> +    "description": "Ibexpenses - Manage your personal expenses",
Change name to Ibex Wallet

2024-10-09 15:06 UTC, MuhammadMaazFaisal commented
@mjawaids Please take a look at this PR. I updated the package files, but I still can not figure out why the check keeps failing. package files with the previous version, exactly as you instructed, but it is still not functioning. I tried running it locally, but it functions properly there.

2024-10-09 15:45 UTC, mjawaids commented
> @mjawaids Please take a look at this PR. I updated the package files, but I still can not figure out why the check keeps failing. package files with the previous version, exactly as you instructed, but it is still not functioning. I tried running it locally, but it functions properly there.

You can check the build error at https://github.com/Ibexoft/ibex-wallet/actions/runs/11257729571/job/31302658302?pr=79

According to the error `Your lock file does not contain a compatible set of packages. Please run composer update.`

You may need to update and then push both composer and lock files to github to pass the build.

2024-10-10 19:13 UTC, MuhammadMaazFaisal commented
> > @mjawaids Please take a look at this PR. I updated the package files, but I still can not figure out why the check keeps failing. package files with the previous version, exactly as you instructed, but it is still not functioning. I tried running it locally, but it functions properly there.
> 
> You can check the build error at https://github.com/Ibexoft/ibex-wallet/actions/runs/11257729571/job/31302658302?pr=79
> 
> According to the error `Your lock file does not contain a compatible set of packages. Please run composer update.`
> 
> You may need to update and then push both composer and lock files to github to pass the build.

@mjawaids I have already done that and tried it again, but it is not working.

2024-10-14 18:33 UTC, mjawaids commented
@MuhammadMaazFaisal ok I've fixed that composer error. Now it is giving error on unit tests. I hope you can now proceed with this and fix the remaining. If you get stuck let me know.

2024-10-15 04:50 UTC, mjawaids approved these changes

2024-10-15 04:50 UTC, merged