XW-56: Categories CRUD operations and logo added
Ibexoft/ibex-wallet pull request #89
Opened 2024-09-17 10:51 UTC by MHamzaBham

2024-09-18 05:27 UTC, mjawaids requested changes

2024-09-18 05:27 UTC, mjawaids commented on public/assets/img/ibex-wallet_logo.png
Two different types of work shouldn't be done in a single comment nor task. Adding logo should be a different task thus a different commit in that task.

2024-09-18 05:27 UTC, mjawaids commented on public/assets/js/custom.js
> +    $(inputSelector).val('');
jQuery is a great library but to be consistent we should write code in either Vanilla Javascript or jQuery, but not both. On the other hand jQuery is dead and is no longer being updated by their maintainers. It is only relevant in legacy code.

2024-09-18 05:27 UTC, mjawaids commented on public/assets/js/custom.js
> +    $('#exampleModalMessage').modal('hide');
We should always update the names/ids when copying code from examples to something that describes what it is for.

2024-09-18 05:27 UTC, mjawaids commented on public/assets/js/custom.js
> +                    // location.reload();
Commented code should always be removed. If we ever need it back we can recover it from git history.

2024-09-18 19:11 UTC, MHamzaBham commented on public/assets/js/custom.js
> +                    // location.reload();
Ok

2024-09-19 12:14 UTC, mjawaids requested changes

2024-09-19 12:14 UTC, mjawaids commented on resources/views/layouts/app.blade.php
> +    <link rel="icon" type="image/png" href="../assets/img/apple-icon.png">
This should be set to Ibex Wallet icons. Please, go through following resources to know more about `link` `icons`.
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link
- https://www.dofactory.com/html/rel/icon

2024-09-19 12:14 UTC, mjawaids commented on public/assets/js/custom.js
> +    $('#addCategoryModal').modal('hide');
Is modal from Bootstrap jQuery based? As far as I remember the latest releases of Bootstrap have dropped support of jQuery.

2024-09-19 22:21 UTC, MHamzaBham commented on public/assets/js/custom.js
> +    $('#addCategoryModal').modal('hide');
Yes, I searched the web and got this "Bootstrap 5 does not use jQuery. It has been restructured to work without it, relying instead on vanilla JavaScript. However, it does allow for optional use of jQuery if desired."
I'll go ahead and update the modal code to use vanilla JavaScript as per Bootstrap 5's structure.

2024-09-19 22:33 UTC, MHamzaBham commented on resources/views/layouts/app.blade.php
> +    <link rel="icon" type="image/png" href="../assets/img/apple-icon.png">
I've reviewed the resources provided and understand the intended use of link icons. 
Now, I have reverted the change to the one that was part of the theme because the current branch/task was not meant to make changes to the icons and logo.

2024-09-20 05:14 UTC, mjawaids approved these changes

2024-09-20 05:20 UTC, mjawaids commented on public/assets/js/custom.js
> +    $('#addCategoryModal').modal('hide');
Since jQuery is no longer maintained we shouldn't use it in new projects. Instead, we would start using frameworks/libraries like React or Vue in the future to create components and will integrate Bootstrap with it.

2024-09-20 05:20 UTC, merged