XW-83 - Feat: change the success popup to success toast
Ibexoft/ibex-wallet pull request #91
Opened 2024-09-21 13:30 UTC by faizahmed1234

2024-09-22 19:17 UTC, mjawaids requested changes

2024-09-22 19:17 UTC, mjawaids commented on public/assets/js/custom.js
> +                $('#transactionModal').modal('hide');
As mentioned on Slack (https://ibexoft.slack.com/archives/C07EKENA213/p1727031886914419), we shouldn't use jQuery in newer projects.

2024-09-22 19:17 UTC, mjawaids commented on public/assets/js/custom.js
> +                            window.location.reload();
These lines are repeated so many times. Wouldn't it be useful to create a function that accepts `message` and call this function at all those places?

2024-09-22 19:17 UTC, mjawaids commented on resources/views/layouts/app.blade.php
> +          </div>
The markup for toast should be in a separate file (partial/segment) and included only where it is needed. Otherwise, this main layout will get polluted with lots of different unrelated markups.

2024-09-23 20:53 UTC, faizahmed1234 commented on resources/views/layouts/app.blade.php
> +          </div>
After creating a partial, should I use it on the main layout or on each page where a success toast is expected?

2024-09-24 07:29 UTC, mjawaids commented on resources/views/layouts/app.blade.php
> +          </div>
Generally it should be used where it is needed, but since toast is something that almost every page would need it so it is fine to use it on main.

2024-09-24 12:47 UTC, mjawaids requested changes

2024-09-24 12:47 UTC, mjawaids commented on public/assets/js/custom.js
>                  $(inputSelector).val('');
Please, avoid using jQuery. I'd recommend to remove the jQuery CDN reference altogether so we get errors where it is being used.

2024-09-24 12:47 UTC, mjawaids commented on public/assets/js/custom.js
> +                setToastMessage("Your account has been deleted.");
Is this message correct, or copy/paste mishap?

2024-09-30 20:15 UTC, MHamzaBham commented on public/assets/js/custom.js
>                  $(inputSelector).val('');
Should we remove jQuery CDN on this task/branch or would it be a new task to remove jQuery and code using jQuery?
Since there is much code using jQuery and especially ajax requests which would need to be replaced (with fetch API or axios or any alternative).

2024-09-30 23:53 UTC, mjawaids commented on public/assets/js/custom.js
>                  $(inputSelector).val('');
Since the scope of work is larger, I'd recommend to do it in a different ticket. Please, coordinate with Maaz on this. 
'fetch' API is recommended, I didn't remember that and suggested axios to Maaz.

2024-10-03 14:10 UTC, mjawaids approved these changes

2024-10-03 14:10 UTC, merged