XW-65 fix: Multiple dropdowns opened at same time.
Ibexoft/ibex-wallet pull request #92
Opened 2024-09-22 15:09 UTC by MuhammadMaazFaisal

2024-09-22 19:20 UTC, mjawaids requested changes
Cannot we just hide any open dropdowns on clicking somewhere else? There must be a better way of handling this behavior.

2024-09-23 04:51 UTC, MuhammadMaazFaisal commented
Can't we just hide any open dropdowns on clicking somewhere else? There must be a better way of handling this behavior.

Bootstrap takes care of this by default, so we do not need to use custom javascript. However, the issue arises from the fact that we have attached a onclick function to the li tag. This means that even when I click the dropdown, it calls the li function. To stop this, we need to use stop propagation on the dropdown, which also keeps the dropdown from closing. For this reason, I had to use custom js. If there is a better way, please let me know.

2024-09-23 12:51 UTC, mjawaids commented
> Can't we just hide any open dropdowns on clicking somewhere else? There must be a better way of handling this behavior.
> 
> Bootstrap takes care of this by default, so we do not need to use custom javascript. However, the issue arises from the fact that we have attached a onclick function to the li tag. This means that even when I click the dropdown, it calls the li function. To stop this, we need to use stop propagation on the dropdown, which also keeps the dropdown from closing. For this reason, I had to use custom js. If there is a better way, please let me know.

Why did we need to attach the onclick event on `li`? Is it related to dropdown or something else? If related to dropdown then wasn't dropdown behaving as expected?

2024-09-24 07:03 UTC, MuhammadMaazFaisal commented
> > Can't we just hide any open dropdowns on clicking somewhere else? There must be a better way of handling this behavior.
> > Bootstrap takes care of this by default, so we do not need to use custom javascript. However, the issue arises from the fact that we have attached a onclick function to the li tag. This means that even when I click the dropdown, it calls the li function. To stop this, we need to use stop propagation on the dropdown, which also keeps the dropdown from closing. For this reason, I had to use custom js. If there is a better way, please let me know.
> 
> Why did we need to attach the onclick event on `li`? Is it related to dropdown or something else? If related to dropdown then wasn't dropdown behaving as expected?

We attached the onclick event to li because we open transaction details when a transaction is clicked.

2024-09-24 07:40 UTC, mjawaids commented
> > > Can't we just hide any open dropdowns on clicking somewhere else? There must be a better way of handling this behavior.
> > > Bootstrap takes care of this by default, so we do not need to use custom javascript. However, the issue arises from the fact that we have attached a onclick function to the li tag. This means that even when I click the dropdown, it calls the li function. To stop this, we need to use stop propagation on the dropdown, which also keeps the dropdown from closing. For this reason, I had to use custom js. If there is a better way, please let me know.
> > 
> > 
> > Why did we need to attach the onclick event on `li`? Is it related to dropdown or something else? If related to dropdown then wasn't dropdown behaving as expected?
> 
> We attached the onclick event to li because we open transaction details when a transaction is clicked.

In that case dropdown click event should be fired before the `li` click event. This can be done by the right sequence of registering click events. Secondly, instead of showing/hiding dropdown ourselves we should rely on bootstrap behavior and we should stop propagating dropdown's click to `li` click. On the other hand 'li' shouldn't click shouldn't stop event propagation as it will allow bootstrap to hide the dropdown.
If there is any confusion shoot me a message and we'll discuss it.

2024-09-24 09:59 UTC, MuhammadMaazFaisal commented
> > > > Can't we just hide any open dropdowns on clicking somewhere else? There must be a better way of handling this behavior.
> > > > Bootstrap takes care of this by default, so we do not need to use custom javascript. However, the issue arises from the fact that we have attached a onclick function to the li tag. This means that even when I click the dropdown, it calls the li function. To stop this, we need to use stop propagation on the dropdown, which also keeps the dropdown from closing. For this reason, I had to use custom js. If there is a better way, please let me know.
> > > 
> > > 
> > > Why did we need to attach the onclick event on `li`? Is it related to dropdown or something else? If related to dropdown then wasn't dropdown behaving as expected?
> > 
> > 
> > We attached the onclick event to li because we open transaction details when a transaction is clicked.
> 
> In that case dropdown click event should be fired before the `li` click event. This can be done by the right sequence of registering click events. Secondly, instead of showing/hiding dropdown ourselves we should rely on bootstrap behavior and we should stop propagating dropdown's click to `li` click. On the other hand 'li' shouldn't click shouldn't stop event propagation as it will allow bootstrap to hide the dropdown. If there is any confusion shoot me a message and we'll discuss it.

Okay, I've changed its approach.

2024-09-24 12:26 UTC, mjawaids requested changes

2024-09-24 12:26 UTC, mjawaids commented on resources/views/transactions/index.blade.php
> +                                                    class="fas fa-{{ $transaction->type == 3 ? 'exchange-alt' : ($transaction->type == 1 ? 'arrow-down' : 'arrow-up') }}"></i>
Instead of numbers for transaction types, constants/config should be used as they are more readable and more flexible, you can change the value if needed without updating the code where they are used.

2024-09-24 12:26 UTC, mjawaids commented on resources/views/accounts/index.blade.php
> +                            <div onclick='openEditAccountModal({{ json_encode($account) }})'>
Instead of rendering with `account` info it is better to pass the account id to the `openEditAccountModal()` function which should asynchronously fetch the fresh/updated account data from the server on demand. This will not only simplify the signature/interface of functions but will also be more flexible and fault-tolerant as it will fetch the updated data from the server in case it has been updated from somewhere else.
Also, consider if we have to develop a SPA client which totally runs on the browser or mobile where we won't leverage the server-side code then what would be the approach. As we will eventually move to separate client applications where we won't have access to blade directives.

2024-09-24 12:26 UTC, mjawaids commented on resources/views/transactions/index.blade.php
> +                                                            style="max-width: 250px;">{{ $transaction->details }}</span>
There must not be any inline styles. All should go in `.css` files.

2024-09-30 17:44 UTC, MuhammadMaazFaisal commented on resources/views/transactions/index.blade.php
> +                                                            style="max-width: 250px;">{{ $transaction->details }}</span>
I have updated all of the mentioned changes.

2024-09-30 18:32 UTC, mjawaids requested changes

2024-09-30 18:32 UTC, mjawaids commented on public/assets/js/custom.js
> +    $.ajax({
No jQuery please. You can use `axios` library instead.

2024-09-30 18:32 UTC, mjawaids commented on resources/views/layouts/app.blade.php
>      <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
I'd recommend to remove jQuery link altogether as we don't intent to use jQuery.
Also, if we're not using SweetAlert library then also remove it too.

2024-09-30 18:32 UTC, mjawaids commented on config/custom.php
> +    ],
Having more thought on the design/architecture, I'd say it would be even better if we have a TransactionType class with all the constants defined in it. This will allow to attach behavior to transaction types in the future which is highly likely. Secondly, configs are usually used for system related stuff or where it could be changed based on the environment while transaction types are business objects that could have business logic attached to it. 
In addition to class contacts also explore enums (https://www.php.net/manual/en/language.types.enumerations.php) if we could use these for transaction types. 
Let me know your thoughts after your research and we'll discuss.

2024-10-09 14:49 UTC, MuhammadMaazFaisal commented on config/custom.php
> +    ],
I have updated the code, you can check it out and let me know, I haven't removed jQuery and Sweet Alert link because hamza is working on that.

2024-10-09 15:23 UTC, mjawaids requested changes

2024-10-09 15:23 UTC, mjawaids commented on public/assets/js/custom.js
> +            alert('Failed to fetch account data.');
Use toast instead of `alert()`

2024-10-09 15:23 UTC, mjawaids commented on resources/views/dashboard.blade.php
> +                                            class="btn btn-icon-only btn-rounded btn-outline-{{ $transaction->type == \App\Enums\TransactionType::Transfer->value ? 'info' : ($transaction->type == \Ap
For better readability, it is better to import the namespace to shorten the reference.

2024-10-09 15:23 UTC, mjawaids commented on resources/views/dashboard.blade.php
> +                                            class="btn btn-icon-only btn-rounded btn-outline-{{ $transaction->type == \App\Enums\TransactionType::Transfer->value ? 'info' : ($transaction->type == \Ap
I don't think of a scenario where we'll need Backed Enums. Basic/Pure enums should work. Just need the check with the database if it is compatible or how we are storing these in database.

2024-10-09 16:45 UTC, MuhammadMaazFaisal commented on resources/views/dashboard.blade.php
> +                                            class="btn btn-icon-only btn-rounded btn-outline-{{ $transaction->type == \App\Enums\TransactionType::Transfer->value ? 'info' : ($transaction->type == \Ap
Can you elaborate on what you mean by Basic/Pure Enums? Are you suggesting that I implement it this way?
```
enum TransactionType {
    case Expense;
    case Income;
    case Transfer;
}
```

2024-10-09 17:58 UTC, mjawaids commented on resources/views/dashboard.blade.php
> +                                            class="btn btn-icon-only btn-rounded btn-outline-{{ $transaction->type == \App\Enums\TransactionType::Transfer->value ? 'info' : ($transaction->type == \Ap
Yes. See below for reference:
https://www.php.net/manual/en/language.enumerations.basics.php
https://www.php.net/manual/en/language.enumerations.backed.php

2024-10-10 18:52 UTC, MuhammadMaazFaisal commented
@mjawaids I have implemented it with Basic Enum; please take a look and let me know.

2024-10-14 17:29 UTC, mjawaids requested changes

2024-10-14 17:29 UTC, mjawaids commented on app/Http/Controllers/AccountController.php
> +                'message' => 'Unauthorized access.'
This is the case where some user tries to access someone else's account, which in theory doesn't exist for that particular user. In that case, error should be **404 Not Found**. 
Unauthorized error means entity does exist but user doesn't have permission to access it, and there might be a way to get those permissions which is not true. This will only be true when entities can be shared between multiple users which is not possible here.

2024-10-14 17:29 UTC, mjawaids commented on app/Http/Controllers/TransactionController.php
> +        }
This is something which we could move to Authentication/Authorization layer as we need this in every controller, thus duplicate code. Addressing this would require its own separate ticket though, no need to do this in this ticket.
Some ideas about the authorization layer could be Laravel middleware, gates, or policies, or we could just use PHP Traits to extract this bit of code and use that Trait in all controllers where needed. Some research required on this part.
Please, create a separate ticket for this and move it to Backlog for now, we'll prioritize it later.

2024-10-14 17:29 UTC, mjawaids commented on public/assets/js/custom.js
> +    console.log(showUrl);
Never leave `console` logs in committed code.

2024-10-14 17:29 UTC, mjawaids commented on public/assets/js/custom.js
> +/* Success Toast */
`custom.js` file is getting bigger. It is better to break it down for each module, but again this should be done in a separate ticket as it is part of code optimization.

2024-10-14 17:29 UTC, mjawaids commented on resources/views/categories/index.blade.php
> +                            ])
Why not just pass the `$category` object itself instead of passing each property separately?

2024-10-14 17:29 UTC, mjawaids commented on resources/views/dashboard.blade.php
> +    use App\Enums\TransactionType as TransactionType;
I think this is not a good practice to `use` a namespace/class here in blade template. They should be `use`d in controllers.

2024-10-14 17:39 UTC, MuhammadMaazFaisal commented on resources/views/categories/index.blade.php
> +                            ])
I don't know, this work was done by hamza in another branch and when I rebased my current branch, others work also started showing in my branch

2024-10-14 17:49 UTC, MuhammadMaazFaisal commented on resources/views/dashboard.blade.php
> +    use App\Enums\TransactionType as TransactionType;
I searched about it, and it said we have to include namespace in the blade file where we have to use it, otherwise it is not working.

2024-10-14 17:59 UTC, mjawaids commented on resources/views/dashboard.blade.php
> +    use App\Enums\TransactionType as TransactionType;
How is it working in `home.blade.php`, we haven't added this statement there?

2024-10-14 18:45 UTC, mjawaids commented on resources/views/categories/index.blade.php
> +                            ])
OK, this optimization is for another ticket.

2024-10-14 22:22 UTC, MuhammadMaazFaisal commented on resources/views/dashboard.blade.php
> +    use App\Enums\TransactionType as TransactionType;
The home.blade file is not used anywhere; it contains the initial dashboard code, I have removed it and pushed again.

2024-10-14 22:22 UTC, MuhammadMaazFaisal commented on public/assets/js/custom.js
> +    console.log(showUrl);
Done

2024-10-14 22:24 UTC, MuhammadMaazFaisal commented on app/Http/Controllers/AccountController.php
> +                'message' => 'Unauthorized access.'
Done

2024-10-15 04:33 UTC, mjawaids commented on resources/views/dashboard.blade.php
> +    use App\Enums\TransactionType as TransactionType;
OK, create a ticket for this issue as well, we'll have to find a better solution.

2024-10-15 04:33 UTC, mjawaids approved these changes

2024-10-15 04:34 UTC, merged