XW-85 fix: Delete option to appear when all subcategories are deleted
Ibexoft/ibex-wallet pull request #94
Opened 2024-09-24 14:29 UTC by MHamzaBham

2024-09-24 14:55 UTC, mjawaids requested changes
What's the business logic here? Is parent category not allowed to be deleted if it has child categories? If so then this has to be changed so that if parent category is deleted, all its child categories should also be deleted, but warn user before deleting it.

2024-09-24 14:55 UTC, mjawaids commented on public/assets/js/custom.js
> +                                            <a class="dropdown-item py-1" href="#" style="font-size: 12px;">
No inline styles. Better to use classes and define them in `.css` files.

2024-09-24 14:55 UTC, mjawaids commented on public/assets/js/custom.js
> +                                            <a class="dropdown-item py-1" href="#" style="font-size: 12px;">
Also, this markup is duplicated in `subCategoryList.blade.php` file. That means if we ever have to change it we have to change it at two places and forgetting at one place could introduce issues. This has to be in one place and used wherever is needed. This is also a candidate for component if we were using React/Vue/Angular.

2024-09-25 14:04 UTC, MHamzaBham commented on public/assets/js/custom.js
> +                                            <a class="dropdown-item py-1" href="#" style="font-size: 12px;">
> No inline styles. Better to use classes and define them in `.css` files.

I have replaced the inline style with a bootstrap class

2024-09-25 14:10 UTC, MHamzaBham commented on public/assets/js/custom.js
> +                                            <a class="dropdown-item py-1" href="#" style="font-size: 12px;">
> Also, this markup is duplicated in `subCategoryList.blade.php` file. That means if we ever have to change it we have to change it at two places and forgetting at one place could introduce issues. This has to be in one place and used wherever is needed. This is also a candidate for component if we were using React/Vue/Angular.

For this, a new blade component for dropdown menu is made and called in both index.blade and subCategoryList.blade

2024-09-26 04:47 UTC, mjawaids approved these changes

2024-09-26 04:47 UTC, merged