Xw 82 update logos and favicon with branded ones
Ibexoft/ibex-wallet pull request #95
Opened 2024-10-12 06:58 UTC by MHamzaBham

2024-10-14 17:01 UTC, mjawaids requested changes

2024-10-14 17:01 UTC, mjawaids commented on public/assets/css/custom.css
> +@media (min-width: 425px) {
Why do we need media queries when we are using Bootstrap? It is better to use Bootstrap classes for responsiveness.

2024-10-14 17:12 UTC, MHamzaBham commented on public/assets/css/custom.css
> +@media (min-width: 425px) {
I used it for specific sizes, but sure can replace it with bootstrap classes

2024-10-17 09:29 UTC, mjawaids approved these changes

2024-10-17 09:29 UTC, merged